name:               miso-tutorial-app-client
version:            '0.1.0.0'
synopsis:           The client side of an example SPA in GHCJS + Miso.
category:           Web
license:            BSD3

dependencies:
- aeson
- base
- bytestring
- ghcjs-base
- miso
- network-uri
- servant
- utf8-string

executables:
  miso-tutorial-app-client:
    main:           Main.hs
    source-dirs:
    - ./
    - ../shared
